project:
  type: website
  output-dir: ../home

website:
  title: "抛锚的云の个人空间"
  description: "It's a personal blog of AnchoraCloud. Some articles, notes and thoughts will be published irregularly. You are welcome to view and comment."
  site-url: https://st-anontokyo.github.io/home
  repo-url: https://github.com/st-anontokyo/st-anontokyo.github.io
  navbar:
    left:
      - text: "起始页"
        href: https://st-anontokyo.github.io
      - text: "主页" 
        href: index.qmd
      - text: "关于"
        href: about.qmd
      - text: "文章"
        href: articles/index.qmd
      - text: "小说"
        href: novels/index.qmd
      - text: "笔记"
        href: notes/index.qmd
  page-footer:
    center: "2026 AnchoraCloud. Done with quarto."

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-copy: true
    include-in-header:
      text: |
          <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Ma+Shan+Zheng&family=Noto+Sans+SC:wght@100..900&family=Noto+Serif+SC:wght@200..900&display=swap" rel="stylesheet">
          <link rel="icon" type="image/png" sizes="32x32" href="/apple-touch-icon.png"/>
          <link rel="apple-touch-icon" href="/apple-touch-icon.png"/>



