project:
  type: website
  output-dir: ../home

website:
  title: "云的锚泊地"
  description: "It's a personal blog of AnchoraCloud. Some articles, notes and thoughts will be published irregularly. You are welcome to view and comment."
  site-url: https://st-anontokyo.github.io/home
  repo-url: https://github.com/st-anontokyo/st-anontokyo.github.io
  announcement:
    icon: flag
    dismissable: false
    content: "<center>**欢迎光临我的个人博客!**</center>"
    type: info
    position: below-navbar
  comments:
    giscus:
      repo: "St-AnonTokyo/St-AnonTokyo.github.io"
      repo-id: "R_kgDOSdYTwQ"
      category: "Announcements"
      category-id: "DIC_kwDOSdYTwc4C9dKK"
      mapping: "pathname"
      reactions-enabled: true
      input-position: "top"
      theme: "preferred_color_scheme"
      language: "zh-CN"
      loading: "lazy"

  reader-mode: true
  back-to-top-navigation: true
  page-footer:
    border: false
    background: light
    left: |
      © 2026 AnchoraCloud

      built with Quarto

  navbar:
    background: light
    foreground: dark
    title: "AnchoraCloud"
    search: true
    logo: "apple-touch-icon.png"
    tools: 
      - icon: github
        href: https://github.com/St-AnonTokyo/St-AnonTokyo.github.io
    left:
      - text: "起始页"
        href: https://st-anontokyo.github.io
      - text: "主页" 
        href: index.qmd
      - text: "关于"
        href: about.qmd
      - text: "文章"
        href: articles/index.qmd
        menu:
          - text: "年终总结"
            href: articles/summary/index.qmd
          - text: "随笔"
            href: articles/essays/index.qmd
      - text: "小说"
        href: novels/index.qmd
        menu:
          - text: "短篇"
            href: novels/short/index.qmd
      - text: "笔记"
        href: 401.html


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    include-in-header:
      text: |
          <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Ma+Shan+Zheng&family=Noto+Sans+SC:wght@100..900&family=Noto+Serif+SC:wght@200..900&display=swap" rel="stylesheet">
          <link rel="icon" type="image/png" sizes="32x32" href="/apple-touch-icon.png"/>
          <link rel="apple-touch-icon" href="/apple-touch-icon.png"/>



