project:
  type: website
  output-dir: ../docs/home

website:
  title: "AnchoraCloud"
  description: "It's a personal blog of AnchoraCloud. Some articles, notes and thoughts will be published irregularly. You are welcome to view and comment."
  site-url: https://st-anontokyo.github.io/blog
  repo-url: https://github.com/st-anontokyo/st-anontokyo.github.io
  navbar:
    left:
      -  text: "主页" 
         href: index.qmd
      -  text: "关于"
         href: about.qmd
  page-footer:
    center: "2026 AnchoraCloud. Done with quarto."

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-copy: true



