---
title: "写给我的2025"
author: "AnchoraCloud"
date: "2026-02-15"
categories: [生活,自我]
comments: false
---

又是一个太阳年过去了，地球也差不多绕着太阳转了一圈，回到它原本的位置，地球上的人却都老了一岁，不再是过去的那个人了。值此年末之际，正是回忆与记录的大好时间。然而因为平时没有记录的习惯，如今临阵磨枪，只参照着大脑里那些碎片化的神经信号，未免有遗落与混淆之误，因此我只着重于那些大体的心路历程，而略过细节之处。

我不太想谈高考，那对我来说算不上多么好的回忆，只有做不完的题目、倦怠、不断的自我洗脑以及操纵我肾上腺素的考试铃声，当然，还有最后那定格的、冷冰冰的分数。这一切都让我有种“行货”感，我像一个在舞台上卖力表演的小丑，赤身裸体、满头大汗，拼命地接住抛上高空的皮球，战战兢兢地走在摇摇晃晃的空中钢丝上，只是为了表现得足够完美，以博取台下那几个评委或观众的喝彩，于是我才有机会搬到更大的舞台上。然而我不得不这么做，因为我需要更大的舞台。现在我已经售卖了自己，虽然价格不比我预想的，不过也还可以，足够未来的我发挥了。但我那时并不开心。

高考后的暑假我陷入一种深深的倦怠之中。我不想学任何东西，我害怕大学是高中的翻版，害怕在那里遇到比高中更厉害、更会做题的人，要学更难的知识，准备更严格的考试，我害怕未来依然是这种无意义的、没有尽头的生活，于是我选择逃避现实，二次元就是个不错的选择。我之前一直觉得二次元的游戏、动漫什么的只是为了给宅男增加性幻想素材的，现在我想也许它们的受众要更广泛一点。暑假的时候我下载了“原神”并且玩了很久。一开始觉得很新奇，你可以操纵一个角色和那里面的人物对话、互动，就像是真实存在的一样。我喜欢抽取一些剧情中我钟意的角色，让我可以操纵她们，只是为了能把她们带到某个风景不赖的地方，在那里四处转圈，看着游戏界面从白天到夜晚再到黎明，就好像我生活在那里一样。但是为了抽取到那些角色，我不得不给出足够的“价格”，这就需要我带着那些角色去和一些丑陋的怪物战斗或是参加各种无聊的活动，这很烦人，但很容易成瘾，这后来演变成某种强迫性的行为，就像刷题刷到最后，我在漫长而无聊的剧情和重复的打斗中感到疲倦，于是我最后干脆懒得抽新角色，而是想象我抽到了她们并和她们对话。再后来，我几乎不需要真正地在手机或电脑上操作那些角色，只要在出新剧情的时候过一遍，结合我过的剧情和那些人物的肖像，我就可以想象我生活在她们之间了。只有遇到我真正感兴趣的角色，我才会出于仪式感想要把她抽取。再后来，我对官方的剧情越来越不满意，总觉得有很多商业化的东西，很多角色的行为与表现仿佛只是为了迎合玩家，很莫名其妙。因为我素来不喜做演员而更喜做观众，如果观众的喜好反过来影响了台上演员的表现，甚至演员完全成为观众的仆人，那么这观众就是不合格的，于是我渐渐地不再玩二游了。

假期结束后，我怀着忐忑的心情步入大学，遇到的第一件事就是军训。那简直让我关于大学生活不安的猜想统统应验了，为期半个月的军事化管理，晚上10点多解散、早上5点多集合，在40度的烈日下反反复复地练习队列，无意义的说教与训话，“左右脑互搏”的校领导，奇葩的内务规则，雨天的穿雨衣淋雨环节……让我印象最深刻的是，在合唱比赛时，评委中仅有一位通乐理的音乐老师，其余皆是各级领导。最后，那位音乐老师认可的几个连队都没有得奖，而他认为表现不好的队伍却斩获冠军。我周围的很多同学都忍无可忍，纷纷到校网上痛骂教官和校领导，结果也不了了之，唯一的改变是我们连的待遇貌似提高了，教官也更和蔼了，高温和雨天也不用训练了……而那些没有表示抗议的团和连则依然重复着之前的日程。这是我在大学学到的第一课，原来世界就是一个巨大的草台班子，即便在所谓的象牙塔，也是如此。你要想保住自己的尊严，就得自己去争取。

等到正式开课，我不安的心情才渐渐平复。我遇到了很多聪明而负责任的老师，他们毫不吝啬地把自己的知识传授于我，并愿意倾听我的问题，给我指出错误。他们都是很有思想的人。教授微积分的卢老师用犀利而幽默的语言带领我们步入一元函数微积分的大门，他的身上兼有学者的自傲与平和；教授线性代数的汪老师经常因为课时紧凑而在课间偷偷吃着简陋的午餐；教授C程的周老师不厌其烦地在群里发考试题型和复习材料，照顾到那些翘课的同学；英语老师总是借着学习文章的契机表达一些她对社会、对人性的见解，在她的课堂上，英语不仅仅是一门语言，更是一扇认识世界的窗户；身体素质课老师很漂亮，她经常能想出一些奇特而新颖的活动给我们上课练习，每节课都不一样……我渐渐沉浸在大学更为抽象、也更为有趣的知识之中，而忘掉那些令人悲伤的心绪，唯一不足的是，我新掌握的东西并不是很多，开设的课程中，有大量我不感兴趣的但为了学分又不得不上的课，感觉一学期下来，只是比高中多了解了一点高数，学会了一些简单的编程而已。不过我学习的感觉已与高中大不相同，即便遇到了挫折，我也不会感到厌烦，我想我以后自己会去学更多东西的。我也说不清这种感觉具体是为什么，也许是因为上面那群人，也许是我已不再为分数所束缚。但我最喜欢的解释还是：我对于自己的未来已经有了一些构想，而在那个蓝图里面，知识是不可或缺的一部分。

除此之外，大学也让我感受到前所未有的自由。虽然仍然有班级、团支部这种东西，但班内同学除了一月一次的班会就很少见面了，互相也很陌生。同居的几个室友也不常说话，平时各上各的课，周末都去图书馆，互不干扰。寝室里很安静，只消拉上床帘，就是我自己的房间。我可以自由地在校园里四处走，而不用跟什么领导敬礼、问好，不用担心遇到熟人要停下来打招呼。这是一个很大的校园，我总能找到没人的地方，安安静静地坐一会或是对着树发呆。我需要这样一种空间，虽然你知道这是学校的财产之类的，但你会感觉到某一个时刻，这片小地方就属于你，没有人和你共享——只属于你。

进入大学也开始让我构想一些大学之后的生活。有时候我不愿意往深处想，因为除了那些可能的事业和自由支配的时间能让我向往之外，其余都是一片黑暗。

在我小的时候，我很喜欢玩玩具。我喜欢拿各种各样的玩具按照高矮摆成一排，有动物玩偶，小熊、小狐狸、骆驼、猴子之类的，也有玩具，比如“超级飞侠”里面那些拟人的飞机的模型，还有铲土车、迷你的恐龙模型，总之就是各种杂七杂八的小玩具。然后，我盯着它们，试图挖掘出某种合理的关联，把它们作为某个故事中的角色串联起来，而我，兼职编剧、导演和演员，指挥并操纵这些无生命的事物演出一场场有趣的戏剧，聊以消磨无聊的时光。当然，这种戏剧绝大部分都是正派与反派你来我往的幼稚把戏，但偶尔灵光一现，我也会想出一些真正有意思的剧情。

在大学里生活了将近半年，我发现生活也有这种类似儿童游戏的部分，那是你可以自己构想、自己建设、自己表演的部分，我喜欢这一部分，并且也有一定的动力去开拓这片区域。我给自己设下规定，哪个时间段做哪件事，不一定是什么大事，只要是我想做的都可以。大部分时候，它们看起来有点机械，像是死板的每日计划，但区别在于，我并没有提前写好以后一整周、一整个月的计划，只有当天的我有权利决定当天做什么事。有时候，我会很认真地去做一些很小、很小的事，就像把一片树叶从一棵树的底下捡起来，挪到几百米之外的另一棵树下，或是突然蹲下来，闻一闻路边不知名的小花的香味。有时候，我会想要去做一些“惊心动魄”的事，就像在夜里十一点钟在教学楼的地下车库里逛一圈，或者故意在农学院的稻田里迷路。

然而，我有时会怀疑，这种自由究竟是环境带来的，还是我真正改变了。当我放假回到家，看到我熟悉的卧室，那些陪伴我十几年的脸庞，颓废与不安重又笼罩了我。我究竟有没有摆脱那个舒适的、顽固的、狭窄的世界呢？我曾经读过一本小书，名叫《德米安》，大概讲的是小说的主人公摆脱懦弱、摆脱他人给自己赋予的人生观念，而勇敢地投向自我的怀抱，打碎了他从小所安居的世界。可是，当我重新回到那个熟悉的环境，生活就不由自主地回归旧有的模式。也许，我该多出去走走了。
我觉得所有人都不可信，不管表面上看起来怎样，他们都是纯粹的他者，不可能真正走入我的内心，我永远能从他们举手投足的一些细节中看到这一点。能够与我交心、伴我一生的伙伴，只有我自己。无论如何，不管我变成什么样，不管我的境遇如何，不管我身边有谁，这一点都绝对正确。好吧，也许这过于偏激，但过往十几年的经验告诉我，这可能是保护自身的最佳方式。

更深刻的自我觉察是必要的，也许这正是总结的意义。以上就是2025的我，我不想再写下去了，这已经足够多了，行动比思考更加有力，比起在家里紧闭的房间内思索，过着父母给予我的，长达18年的生活，还是去外面，去远方吧，那里才是我真正的归宿。
