---
title: "写给我的2023"
author: "AnchoraCloud"
date: "2024-02-27"
categories: [生活]
comments: false
---

2023年，是疫情开放后的第一年，相较于大军压境的新冠，打游击的甲流就不太成气候。万物复苏，我的生活却和居家那几年没什么不同。太阳照常升起，我也照常过我的日子。想到我在《写给我的2022》这篇文章里还说疫情后要出门远游，现在倒觉得有点可笑。我发觉我并不是很喜欢旅游，明明在电脑上就可以看到照片，何必亲自去呢？况且，心灵足以抵达五感远不能及的地方。因此，相比于关注离我遥远的那些所谓的名胜古迹，我更关注我身边的事物，在这些事物中，心灵使我可以“举类迩而见义远”，从中发现无尽的乐趣。我这一年，就是这样坐在家中，在思想观念上完成了一些重大的转变。

纵观这一年里遇见的人和事，要说给我带来的影响最大的，还是书籍，虽然我看的并不多。毕竟我真的没有什么特别的经历，痛苦和快乐对我来说只存在于一些小事中，像是应付莫名其妙的考试，或是听到了一首调起我情绪的歌。没有体验到的苦与乐，我在书中找回了它们。

列举书的内容就没意思了，但通过小说里人物的起伏，我感受到了平常生活中很难体会的情感，我很快就会把他们忘掉，但他们对我造成的惊奇和影响，却会留在我这儿，等着我慢慢知晓。

小说往往是浓重的，它表现的是另一个世界。毕竟还是震撼的事使人印象更深刻；受着感情的影响，人对现实的估计也往往有些夸大。小说的丰富多彩，与我平平淡淡的生活形成了鲜明对比。相比于那些动不动就要死要活的人物，动不动就走个两万五千里长征路的人，我每天从家到学校那点距离小的可怜，而且如果我眼睛不瞎，总不至被车给撞死。这样一来，依照某些通俗小说的逻辑，我好像就低人一等，因为我有再奇妙的想法，也只能想想，没法付诸实践。这一年里，我有过无数关于未来生活的想法，但无疑，它们都成不了真，因着现实和我自己的缘故。

罗素说过：“一切伟大的著作都有令人生厌的章节，一切伟人的生活都有枯燥无聊的部分。”照我看，这种部分可能占据了他主要的人生。并且，我们中的大多数——绝大多数——都过着日复一日的平凡生活，很少有波动。我们固然是可以歌颂英雄、歌颂烈士，把自己的生命寄托到一个伟大的东西上，像是“自由意志”、“人类文明”、“共产主义”、“正义和智慧”云云。但是，难道我们平日里的事物就不值得歌颂吗。事物的价值，是可以被量化而比较的吗？在我看来，假使有一个观察者的存在，无论是什么样的事物，都会被赋予某种意义。相比于那些宏大的概念、理想，当我凝视我的钟表，想到它每天都在坚持给我计算时间，让混乱的世界有了秩序；当我走下学校的楼梯，想到每日它都支撑着2000余人，上上下下；当我发现我手边这本新华字典可能是汇集了成百上千人的智慧——统计、编纂和校订——才最终成书，做成它的纸来自各省的工厂，而工厂的木材有来自不知是哪的森林，森林中树木需要阳光、水分和养料，它们的祖先又是从哪里进化来的......当我进一步察觉到这些事物的存在时，我就感觉它们好伟大、好奇妙。这种景象，又何尝不是一种奇迹？

这就是我思想观念的转变，从前我很喜欢一些宏大的事物，恨不能把自己的一生都投入到其中。到如今，我终于明白了史铁生的一句话“生活不是为了写作，而写作是为了生活。”写作，是为了发现生活中的细微之处，从中窥得一丝生命的、世界的真实。

真正的小说应该是反映生活而不是讲道理、谈理想的，真正的小说写的是平凡人、平凡景，而不是伟人、眼花缭乱的名胜古迹。我看卡尔维诺的小说，他的文字平淡而奇妙，人物细微的动作间有种演说家手舞足蹈都不能表现的真意；对于红楼梦里的一些情节，为了考试而飞速阅读，看不懂那些需要细细品尝的生活之意，我在过去就犯了这个错误，导致都没有看完就不耐烦地放下，这几天看了蒋勋对红楼的解读，又燃起了一些重读的信心，等待一个好的时机，反正一定要在高考之后。

除此之外，在未来的一年、两年、十年里，我想更多地关注我的生活，而不是书中的生活。虽然我的生活实在没什么可圈可点之处，但我希望通过我的建设让那些平凡之物绽放出不平凡的光彩。我想，这一切都在我，当它们经过我手中，也就带上了一层我的气息。我希望以此与我的生活建立更加深入的关系。我的一日三餐、每日的洗漱、和父母的相处细节、学校的琐事，我希望全部知道它们，尽可能认识它们，适度地改造它们，不要破坏它们。这是我对未来一年的期望。

2023年，我积累了太多疑惑，我希望在生活里破除它们，思考是必要的，生活也是必要的。2023年，我在后者上并没什么体会，在前者上又有点漂浮。我向2023道一声歉，为我的不真诚，没有认真体会它，因而在我眼中2023和过去的其他年份一样都没什么区别。我会用行动告诉2024，我曾经来到过这个时间。这也是我对2023的一个答复，它至少给我带来了一些转变。
