---
title: "写给我的2022"
author: "AnchoraCloud"
date: "2023-02-04"
categories: [生活]
comments: false
---

2022年，对于我来说，是极为特别的一年。

毕竟，在这一年，我经历了人生中第一次真正意义的大考——中考，并且发挥得也并不算不尽人意。中考前做过大量准备工作，怎么都觉得还不够，但中考后确是有些不在意，感觉中考像是很久远的事了，但去年的这个寒假我做中考复习规划的样子却仍历历在目。我想，中考本身除了让我圆了“四中梦”，倒也没有带来多么深远的影响，毕竟它并不像高考那样决定一个人的命运。

初中毕业后的那些同班同学，除了与我同在一所高中的，都不再联系了。说实话，我也并不怎么怀念他们。我还记得我在小学毕业后的一周里曾无比怀念与伙伴的时光，恨不能与他们共读同所中学，而这种感情现已淡漠了。我起初怀疑是长期的居家线上学习和网络生活让我变得冷漠，家与外界仿佛产生了一种隔膜。居家的生活比之学校生活是单调的，诚然，网络生活是丰富多彩的，但它总归是虚构的。一个真实的人不能总活在虚幻里，这就带给我一种空虚感。

这种隔膜并不全是强制性的。要说一开始居家，也即在2019-2020的那些时光里，我是为了生命安全居家，那么现在，可以说居家已经成为一种习惯了。前几个月得知要在家上网学习一点也不惊讶，很是熟练地操作电脑。而2022年的居家时光有些不同，因为有一段时间我产生了怀旧的感觉，我曾怀念过去的那种生活，活动空间还不仅仅是家这样小时的生活。当空间缩小，时间增多，我才得以观察到身边事物的可贵。例如，我留意到一本几年前读过的书，封面已模糊，重读一遍更是颇有感触；每天进出房间都能路过的一张小学毕业的年级合照，头一次蹲下来仔细看看，找找我和我所认识的人也颇有乐趣。身边的事物若经观察都能这样美好，那在家之外的地方，岂不是有更多值得快乐的事物，但我却没有印象了。我无比埋怨自己在这样的生活中变得麻木，对那隔膜外的东西没了什么渴望，有时也会迁怒到能正常上下学，能够到远方看一看的我没有珍惜那种快乐、留下深刻的记忆。正是在那段时光里，我无比珍惜时间、珍惜当下。当我听到政府放开政策时，本来还兴致勃勃，想要一览祖国河山、世间美好，却又面临一场大病，把我的野心都烧回去了，算是让我体会到了几年前躲在家里恐惧而不想体会的痛苦，这让我现在仍心有余悸，还是老老实实待在家里罢。

这样想来，我还是要感谢我的2022年，在这一年里，我看到了很多东西，其中最重要的便是自由的美妙。还是要感谢《澡雪》，让我认识到了一些同样向往自由的人，例如王小波。当然，自由不是毫无限制的，她应是建立在良知的基础上的。物质上不能完全自由，那么精神总应是向往自由的。在客观事物面前，不同的思想会造就不同的主观认识。希望在未来的日子里，面对世界的将是一颗自由的心，我也能从生活中，更大的视野里看到更精彩的世界，发现更多的乐趣。
