---
title: "写给我的2024"
author: "AnchoraCloud"
date: "2025-03-08"
categories: [生活,自我,性]
comments: false
---

又是一年过去，我还是老样子，总觉得平时有千言万语想要找人倾诉，到了这种总结的时候又像是都忘记了般，脑里一片空白。回首看时只看到碎片般的回忆，散落一地，熟悉又陌生。

可是情感却比其他东西要更难忘、更刻骨铭心。我在这一年里，一直处于不安全感中。我总感觉我活得不如从前那样自在了。我还记得2023年，我刚16岁那会儿，我畅想过未来，我觉得我未来肯定能做出一些大事。是什么事还不知道，可就是十分笃定。我那时对于万事万物都很有把握：它们不会阻碍我，只会帮助我，我最终会在自我实现中得到真正的自由。时光辗转，到如今，我仿似变了个人，好多我以为我明白的事都想不明白了，好多原来能轻松做的事都不会做了，好多快乐都离我远去。我感觉不知什么时候，我走上了一条独木桥，四方是湍急的水流，我踏着摇摇晃晃的桥，战战兢兢，一步步挪动。

可笑的是，我连我到底怎么变的都不清楚。我讨厌改变，我想要和从前一样，顺着从前的想法、从前的习惯，去面对以后的生活，这样我才心里踏实。然而天不遂人意，我不得不承认，我已经变了。即便为了安全感再想变回去，我自己也抵触。

说了这么多虚的，还是讲讲这一年里的事吧。大部分事一时都想不起来了，只有近前的事还略微清晰一些。有一次学校组织去南海子公园的秋游，我根本没听说过那儿，心想又得浪费一天时间。到了那儿，发现确实没什么意思——除了一处地方，那里能看麋鹿。我于是直奔麋鹿苑去，有一些同学跟我一块儿。我们兜兜转转，先是进了一个满是孔雀的林子，它们就像鸡一样，不怕人，脖子一前一后地摇，不知往地上啄什么呢。然后又看到鸭子，说不出什么品种，它们见到我们，一齐从湖的远处游来，上岸要了吃的，又一齐离去——它们不管做什么事都要一起做。在那湖里，还见到两只黑天鹅，一高一矮，同样的瘦，高的那个在用嘴给矮的理毛，两个脖子弯到一块拼成爱心的图案。我没敢打扰它们，喂完鸭子就走了。

后来走到一座桥上，桥两个侧面的壁上张贴着古代名人写的句子，都是关于这个公园或者鹿的，有诗有词，乾隆和嘉庆的诗最多，墨子的“墨”字被撕了一半。

走过这个桥，看到标识，才发现走过了，麋鹿苑被我们落到后面了。有的人懒怠折返，就继续往前走。还剩下四个人，我们还是想回去看看。又是兜兜转转，穿过灌木丛，才看到一片围着铁丝网的草地。到了门口，才恍然意识到这种地方一般是要花钱才能进的，而我们谁都不愿意买这么贵的票，于是另辟蹊径，找到一条小路，绕到麋鹿苑的后面，隔着一层铁丝网看鹿。

那些鹿看起来都没什么心情，都缩在中间的树荫底下，迎接买了票的游客，没发现角落里的我们。只有一只马鹿，看着不聪明，来铁丝网边上慢悠悠地啃草。我隔着铁丝网给它抛了一片薯片，掉在地上，它飞速地捡来吃了。因为食物不健康，我没敢让它多吃，就拿片叶子逗它，它很快转头不看了。

我们觉得乏了，又绕了一圈麋鹿苑，随便拍了点照片，就往回走。路上我们接连拿手机放歌，以消解行路的无聊。我们在路上遇见了之前跟我们分开的那批人，然后就是无聊的返程之路了。

写了篇简短无聊的游记，意思意思，算是对去年的具体回忆。这经历还不赖，可我不可能天天去公园，天天看动物，我还是得应付很多杂事，高考就是一件。说到高考，我倒是没有那么紧张。原因是：小学时，我就设想过高考，五年级有一段时间我一直处于对高考的紧张中，整天假想考试失误的事，夜里睡都睡不好。所以紧张基本上用完了，我现在只剩下平静以及麻木。

玩刚才讲过了。而我学习已经麻木了，对这方面没什么回忆，就是在重复一套流程而已。在生活方面，就更谈不上了，一天到晚待在学校，周末家里也死气沉沉的。我好像一直在做我不怎么喜欢的事。我当然知道我不该浪费生命，可是如果不这样做，我连那层基本的社会的安全感也将失去了。

我的精神就是这样一天天消沉下去。这期间我看了一本书，书名是《麦田里的守望者》，里面的主人公很能贴合我的遭遇。可是我看完之后更难过了，难过的要命。那里面写“成长是人必经的溃烂”，之前没人跟我说过，成人礼上也没有人警告过我，我早已不自知地走上这条不归路。我不是说我厌世，厌恶成年之类的，我只是为自己感到难过。我和他一样，被自己困在了一个狭小的空间里，数不清的枷锁束缚着我，我有时候简直不能呼吸。可你要我挣脱出来，这很难，因为正是我自己的手臂在辖制我，我自己的意识在吞噬我。我想逃离，却发现无处可走；要把它讲给别人听，更是不可能——他们会拿一种微笑来对付我，这微笑里大概也有善意吧，可只教我心灰意冷，我只要一见这微笑，话就堵在喉咙里，一句也吐不出来，只有灰溜溜地逃走罢。

对了，还有《红楼梦》。可能因为语言问题，我对于古代的白话文有些不适应，这本书看得很慢——到现在还差一些呢。这大概是本有女性主义倾向的小说，所以我看着很舒服，就是对贾宝玉不大喜欢。那几个女孩，我都很仔细地去读关于她们的一些细节描写，沉浸在她们构建的那个女儿王国——大观园里。这的确帮我消解了一些忧愁。可我知道结局，男人们还是赢了，女儿输了，大观园的梦全被他们毁了。

我于是也开始为女孩们感到难过。这个世界上总有不少蠢货和混账，把破坏美好事物当作乐趣。从古至今，漂亮的女孩会因为美貌而不敢一个人走在街上，相貌平平的女孩则要费尽心思伺候某个蠢货，怕他抛弃自己。这种现状实在是我从前所意料不到的，这和我的理想完全颠倒过来了。在这个世界上，丑的力量太强大了，美是无比脆弱的。我从前都只关注美，沉浸在幻想里，最近才明白，不去仔细研究丑，就没办法维护美，让它延续下去。

现实终归是要教理想破碎的，正因为它与我理想的差距，我才像个怨妇般在这里唉声叹气，整天活在隐晦的恐慌中，没有安全感。纯粹的理想主义者一般下场都不怎么好。顾城就是一个无可救药的理想者，我也无可救药地爱上了他。他太在意自己的理想，于是在看清楚理想不可能实现时就发了疯，落得那种结局。相比之下，我很羡慕宝钗，她就绝不可能发疯。她永远冷静地与现实周旋，把自我藏在深处，披上现实的保护色，去找自己的出路。有时候我忍不住痴想，我要是也有冷香丸服用多好，这样我就能使杂乱的心灵冷却，可惜和尚道士找不上我，我是唯物主义者。

除了这些消沉的想法，我还发现好多我不懂的事。比如说，性。我真的搞不明白它。从小到大我都觉得这是淫秽而邪恶的，每个人都这么暗示我，一谈到这个话题就都噤声了，实在令人困惑。但现在突然有人告诉我，性是自然的、美的。我于是找了一本李银河的书看，看到里面用各种数据，各种科学的方法来分析它，分析得头头是道，就不由感叹，哪里都有这群人，他们一直在努力发明一套理论、运用一种严谨的表达去阐释现实里的每一现象，希图用人类的语言使人完全理解它。说实话，我挺佩服他们的，尽管我清楚自己和他们不是一类人，可还是热衷于学习他们的理论。但在性这一方面，他们还是没让我完全搞懂。他们说性是平等的，可实际上并不是的。在人的眼中，性交是分主客体的，主体对客体施加侵略性的行为。比如，在性交中，男人骑在女人身上。任何一个主观的人，看到这场面，都不能够客观地说它是平等的。任何一个有尊严、有自我意识的人都不会屈居客体的位置，尤其是在平等主义盛行的今天。我在性欲这方面比较慎重、克制，我不想去祸害别人，尤其不想祸害女孩。当然，我看这本书也收获了很多，丰富了这方面的知识，了解了社会的多样性，观念也得到更新。知识总归有点用处，不管是什么样的。

到现在，我仍然在蛮荒的海里浮沉着、漂泊着，对前路充满不安。照理来说，文章的末尾总要谈点积极的，或者升华一下主旨。譬如，既然理想与现实有差距，就该学巴尔扎克那样说：“我可以摧毁一切障碍”。假如是从前的我，我可能真会这么写，可现如今这种话我实在说不出口，只能像卡夫卡，开玩笑似地自嘲：“一切障碍都可以摧毁我”。我想，再熬一熬吧，看看高考之后怎么样，能不能多些闲暇好好想清楚，如果不行，那就继续等，哪怕等到死前那一刹那想清楚也就好了。其实说到底，这何尝不是种乐观主义呢？人生的绝大部分真正的觉悟与快乐，不都来源于漫长的等待吗？我实在不必欺骗自己，说自己有多么多么坚强，精神上仰仗着多么多么伟大的东西，还是就把自己当成个卑微的、惶惑的生命，在人世间苟且着，时不时望望远处干净的天罢了。
