---
title: "独行才能如众"
author: "AnchoraCloud"
date: "2024"
comments: false
word-counting: "1240"
categories: [自我]
---

大部分人生于世上，都是不甘平庸的，希求把自己与别人区别开来，以彰显自身的独特。他们通过个性与偏好确立了自我。而我私以为，凡真正确立自我的人，多少都有点特立独行。

平庸的人会指责那些特立独行之辈，认为其脱离社会、脱离大众、与人疏离，是怪胎。

我想说的是：越是向内确立自我的人，越是能向外体察世界。假如我没有自我，我就相当于不存在；假如世界里不存在我，它对我而言又有何意义？大自然慷慨而包容，为每个人都预备了不同的体验，人体会后，把它表现在诗歌、绘画、歌声里……经久不衰。没有自我的人只能像动物那般，从自然的怀抱里获取最基本的信息：自果树中看到食物，自平原上看到栖息地，把风雨当作回家的号角……他仅仅是为了生存而生存，他只是一个生命体，而非真正的“生命”。缺乏自我带给人的生命力，是无法理解同样具有生命力的自然的。对于他身旁的人们，则更是如此。没有对自我构成的了解，怎能发觉他人的个性，从而理解他人呢？

于是，想要立足于世，首要目标是了解自我。我们当然不能像外科医生解剖别人那样解剖自己，把自身的每个特性一个一个拆解下来，分析一番，最后发现怎么也装不回去了。那会导致自我怀疑以及自我分裂。凡人的生活必定不完满，他所坚持的己见也总有荒谬之处。别人也许会从这些地方攻击他，但倘或他自己也反过来攻击自己，展开自我辩论，就将陷入反复的、矛盾的痛苦之境。假如他的想法不会危及他人，怎样去做应是他的自由，尽管其中有不合理的地方。《树上的男爵》讲一个人终身住在树上，很奇怪。别人都搞不懂他为什么这样做，连他自己也解释不清。他就这样很无厘头地在树上待了一辈子，竟展示出一股愈发强劲的生命力。现实里，我们的所为也许不比他那样夸张，但在对待自我的方面，我们无疑需要一种莫名的执着，坚定地执行自己最初的决定，坚守一生。

这种执着来之不易，但它是通向完整自我的唯一的路，怀疑的、犹豫的自我是不完整的。自我的各个要素应被执着的拉力统一在一起，我们才可安心。

为了维持这种执着，我们也许需要把目光投向外界。要维持自我，一个最直接的做法便是向外界表达自我。自我表达的形式应尽显夸张，就如婴儿出世要大声啼哭、狼要对月长嗥、五爸要到树枝上行走。通过夸张的手段，我们把自我定格在他人眼里，也定格于自己心中，两相加和，就相当于把自我固定在世界里了。这一形象也许不合理、也许荒谬、也许矛盾，但只消让其倾泻而出，形成一盘大杂烩，所有想法在其中疾驰，所有行为互相映照，哪管它正确与否、矛盾与否！我存在于世，我矛盾地存在着，但我存在。这时，一切矛盾都显得统一了。这股存在的力量反过来深化了我们自我的执念，进而巩固了自我。

世界接受我的倾泻，回我以包容。这时，我能看见更多人，那些真正存在于世的、分裂而完整的、矛盾但统一的人，而非那单薄的“人民大众”的形象。他们有各自的好恶、各自的主见、各自的原则，还有各自的矛盾。我真正处于这个整体之中了。世界似乎也有自己的意识，把我们这些也许看似水火不容的人汇聚到一块，编织成一个参差多态、完整的大千世界。
