---
title: "看不见的距离"
author: "AnchoraCloud"
date: "2023-10-10"
comments: false
word-counting: "1394"
categories: [自由]
include-after-body: 
    text: |
        <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js">
        </script>
        <span id="busuanzi_container_site_uv">
          🎰本文阅读量<span id="busuanzi_value_page_pv"></span>次
        </span>
---

记得某一天的体育课前，我站在操场上，望着眼前的一切——做运动的人，心神忽然有些恍惚。我感到自己仿佛穿越到万年前的坦桑尼亚大草原上，身着寸缕、挺直身姿，欲同身旁同伴开启一场猎杀，追逐羚羊。我后来意识到，这是我长期跑步的缘故。

我写下这个奇怪的幻象，是希望读者能够注意：我身在北京，心神却飘到非洲；我还在21世纪，思绪却飞到万年前了。显然，这里包含了两种距离，一种是物质间的距离，另一种是心灵上的距离。

它们似乎都在对我们的生活产生影响，那么，究竟何者对我们而言更有意义，或者说，更值得探讨呢？

我想，人是受其主观思想支配的动物，一个人的情感、言论、行为无不源自他的主观想法。客观距离固然会影响他的判断，但最终呈现在他内心深处的，却是心灵的世界。心灵对现实进行了很大的删减、修饰、补充，以至于心灵世界与现实差异巨大。唐代诗人王勃有诗云：“海内存知己，天涯若比邻。”他只要想到自己远方的朋友，顿觉身处何地都与他同在。但与此同时，他却可能对身边下人、行路时擦肩而过的陌生人视而不见。在心灵世界里，他与朋友很近，与身边人很远。由此来看，心灵上的距离，对我们而言更为重要。

当我们看到科技轻易改变了物质间的距离，我们不禁要问，这更重要的心灵距离该如何跨越？

答案是：随心所欲！只要心有所想，我们就能抵达任何地方，全然不受现实的束缚。苏联作家索尔仁尼琴充分明白这一点，回忆他锒铛入狱的那段时期时，他曾说：“有的犯人会设法冲破铁丝网逃脱！但对我而言，铁丝网根本不存在。犯人总数并没有减少，而我已飞到远方去了。”心灵世界的广博让我们得以跨越任何现实距离，打破现实的限制。纵然我们无法决定我们的位置、身体、样貌、处境……但我们的心灵却可以在尘世中自由来去。

然而，我需要提醒诸位，“随心所欲”一词并没有表面那样简单，它包含了一些隐喻。

首先，既然是“随心”，那我们希望在现实中跨越的距离需先被心灵跨越。索尔仁尼琴没有冲破面前的铁丝网，却早已冲破了他心灵世界的铁丝网。心灵世界应足够宽广，我们的认知才不致使我们受限。一个人的成长历程，便体现了这一点。当孩子与大人同样渴求一样东西时，孩子大概只能够想到向父母撒娇请求，而大人显然想得更多，他拥有更多知识和智慧，自己想出、选择追求的方式，从最便捷的道路跨越现实的“距离”。另一方面，倘我们希望在心灵中抵达某处，我们需先了解它，至少有个轮廓，才可开启想象之旅。因此，我们应不断以行动和智慧开拓心灵的世界、跨越心灵的距离，否则，我们不过是处在一个更大的牢笼里罢了。

再者，“所欲”二字也极可疑。何为所欲？这是些我们发自内心的、真正想要跨越的“距离”。我们应当明白，总有我们一生都不愿跨越的距离，也有我们想立即跨越的距离。人的生命本就有限，用到什么地方也是一种智慧。闻一多早年在家中治学，不断拓宽经学上的边境，却郁郁寡欢。当他出门远游，目睹了国人的苦难，忽然有了一个更强烈的欲望。于是，他投身革命，在那里释放自己的精力与热情。每个人都有不同的欲望，只有辨认出它，我们就能迅速跨越与它的距离，获得巨大的快乐。然而，有的人终其一生都没有找到它，在成长中失去本心。在这点上，孩子倒比大人更加真挚了。

作为一个幸运地找到“所欲”的人，闻一多说：“我的世界还有更辽阔的边境。”诚然，我们既要不断拓宽心灵的边境，更需确保那是“我的”世界。如此，我们才能飞出现实的牢笼，在自己心灵的世界里获得最大程度的自由。
