---
title: "随想"
author: "AnChoraCloud"
categories: [哲思]
comments: false
---

真实是什么，真的很重要吗？古往今来，多少科学家、哲学家献身真理，发掘这世界的奥秘。然而，我们还看到另一个群体，他们不向往真理，永远活在自己的世界里。他们信神、信命，有时以一种狂热的姿态出现在世人面前。我们对他们的印象是顽固、迷信。自诩为理性的唯物主义者，我们只是尊重其作为人自由选择信仰的权利，对其中内容，却是不屑一顾。

这也是我们常爱批评他们的，以一副超脱的面孔，哀叹道：“人们只相信他们愿意相信的。”我却有个疑问，人难道不该相信自己愿意相信的东西吗？

人一诞于世上，他第一个要为之负责的，就是自己。自己的愿望、想法都该被凝神静听。然而，理性主义的浪潮却打断了这一进程。科学教育人，这世上一定有一种真理。人们把这观念套用到自己身上，他的一切欲望，一下子被泼了一桶冷水。当你用理性的眼光审视自己，你会发现自己身上有诸多不合理之处：我怎能那样崇拜一个人呢，人人理应平等啊！我怎能懈怠学业呢，学习是我的天职啊！我怎会对那个观点这样着迷，我该中庸一点，不轻信别人才对啊！……这时，人就惶恐了，赶紧对脑中的想法不断精挑细选，经过长时间的“努力”，他终于成为一个正确、理性的“大智慧者”。

当人达到这样一种状态，外界再不能影响他，他已超脱于凡世，近乎成圣了。他的灵魂升至苍穹，俯瞰人世，平淡地看着世间百态，啧啧摇头。与此同时，他也失掉人性了。

也许你会说，现实里种种反智的争端，譬如互联网上，那万众狂热的姿态，难道不该被批判吗？难道不该用理性管教他们吗？我却认为，在当今时代，理性泛滥了，所缺乏的恰是非理性。那互联网上聒噪的，在现实里又如何？再者，一片听上去嘈杂的森林里，其实只有蟋蟀和鸟在鸣叫，大树、野兔、老虎、蚂蚁，都隐蔽在嘈杂声中，暗中观察这一切。那现实世界里沉默的大多数，哪个不是为生活所迫，想方设法做出理性的抉择，在社会交错纵横的脉络里小心翼翼地做那庖丁解牛之事，见缝插针，开出一条通路？至于那些少数的知识分子、学者，在汲取广博的知识后，痴迷于真理，生活里却少了些火花，谁又没作过浮士德之叹呢？倘没有非理性，不认为自己之所想所为为必是，倘不相信那些“无知”的想法，伟大的艺术家、音乐家、作家都将失业。因为探寻真实的人，不会为心底那些“诱人而愚蠢”的呼唤所动。

我并非在挑战科学，我当然也没有那样的底气，我只是觉得，人心中的某些空间，不该被所谓真实挤占、粉碎。那本来是个不存在真伪的地方，人却因其理性——也许还有怯懦——而不敢去探查。人太忽视自己的欲望，主动去扼杀它们，不愿成为狂热的教徒，害怕为世界所耻笑。但人难道该被世界定义吗？世界如何运转，我就该顺从它的规则——那所谓的正确吗？倘我内心渴望一个神，纵使世界里没有上帝，那我便在心灵里创造一个，聊以慰藉；倘我羡慕鸟类，纵使人类无法飞行，那我便在梦境里翱翔于天际。人的心灵其实是另一个世界，不受什么客观、科学的规律的约束。你无需听从外界的指使，你是它唯一的主人，你可以定义“真实”。

我仍希望人们可以把一些违背正确观念的欲望带到现实世界里，“更改”一些既定的真实。实际上，倘前人无人去做这种事，世界便只是一个正在膨胀、终归热寂的宇宙，地球只是太阳系里一颗“既普通又特殊”的行星，生命是一场偶然，是有机分子作用的结果，它们无时不遵从自然选择定律。

看吧！世界绝不会如今天这般丰富多彩。
