---
title: "我之应试观"
subtitle: "仿鲁迅体"
author: "AnchoraCloud"
date: "2023"
comments: false
word-counting: "1116"
categories: [社会]
---

又是一年一度的高考周，考生将郑重踏入考场，家长焦虑等候，老师几度感慨。一个小小的考试却会在某种程度上决定一个人的未来，令人不免悚然。

这种传统由来已久。隋唐以来，就有科举考试，年年都来一遭，深植入中国知识分子的心底。当下的应试教育体系，则已普及全国各阶层，更有几分科举的影子。
面对这应试的传统，历来就有不同的声音。

对于机械应试之纰漏，大致有三点质疑。

其一，考生十年寒窗，实在为考试逼得太苦、太累。整日发疯似的“内卷”、研究考试策略，属实能把人逼疯。“范进中举”绝非个例。仅仅是为了得一个分数，竟作出这样大的牺牲，到考中了，反而疯了。他所欣喜的分数背后，除了功名利禄，还有什么呢？可见分数如此病态地根植其心，反过来奴役了人。

其二，中国学子整日沉浸在刷题中，可很多人根本没学进去，只知做题，学不到精髓，思维死板、机械。到头来，努力了12年，也未见得取得多高的分数。

其三，从小培养的应试思维很容易让人缺乏后劲。不知多少人，高考完到了大学，便一改往日刻苦模样，整日玩乐、虚度时间。这是儿时活得太累的后遗症。

以上的质疑我皆同意，但凡事所以存在，必有其存在之道理，应试也如此。

无论它有多少缺陷，这种制度无可置疑地给予了所有考生平等的机会，给予底层人民翻身的希望，哪怕只有一丝。再加之中国庞大的人口，一个大规模选拔人才的应试体系是必然出现，也将持续存在的。

谈到这里，我心知任何中国人都无法置身事外，我也不可能完全作为旁观者评判这一制度。

我想，这既是不可避免之事，我们便不该将其视如洪水猛兽，避之不及，而更应迎难而上，将其视作我们实现自我价值之垫脚石。在我们强大到能无视这些阻碍前，我们只得适应环境。然而，我们也不必过分看重它，只是顺其自然，便足矣。它就好比大海中的一股洋流，有的人被它幸运地推上岸，有的人则被推至风口浪尖，抵达彼岸的希望渺茫。在此间，我们能做的，大概只有借其力，顺着它的大方向，找到自己的小方向，并坚定不移地朝那里游。最终，我们兴许还能借助它的力量，抵达我们的彼岸。《红楼梦》中薛宝钗所云“好风凭借力，送我上青云”也许正是她在那黑暗时代里最现实、却也最乐观的美梦罢。

我们既无奈地接受了这事实，那么，那些在应试中失败，一生碌碌无为的不幸的人便命该如此，作出毫无价值的牺牲吗？

不，他们至少还有哀悼的价值。当我们赞美那些跃过龙门的鲤鱼，我们也应关注到这些死在门前的鱼。他们是应试体系的病胎，是“内卷主义”的末路鬼，在激烈的竞争中丧失了一切。这难道不值得那些跃过龙门的，和那设置龙门的人反思吗？

我们自然要留有一份希望。那些幸运地迈过门槛的人，应当发出这愿景，愿这洋流再和缓些，愿后人轻松些，愿世上再无人如范进般被时代耍弄，愿天下人皆搏得自由。
