---
title: "梗文化之我见"
author: "AnchoraCloud"
date: "2023-11-12"
comments: false
word-counting: "2961"
categories: [社会,自我,文化]
include-after-body: 
    text: |
        <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js">
        </script>
        <span id="busuanzi_container_site_uv">
          🎰本文阅读量<span id="busuanzi_value_page_pv"></span>次
        </span>
---

### 初步感知

我几乎没玩过“梗”。

之所以说是“几乎”，是因为我无法排除某些特殊情况。长期置身于玩梗的环境里，有时说话说多了便容易控制不住自己，脱口而出些自己也不明白含义的梗，此类情况终归是少数，但为了严谨，加个前缀也罢。

从客观上来讲，我目前几乎不怎么关注网络上娱乐类的东西，我指的是那种热门的视频与时事。我从不把看梗、笑梗、玩梗当作娱乐，我有别的消遣方式。虽然感觉周围的人几乎都在玩梗，但是由于我心灵的逐渐成熟，我对讨好别人以融入集体的渴求几近消失，因此也不很在意。

从我个人来讲，我觉得所谓“梗”都是别人造出的话题，若要达到幽默的效果，我更倾向于创造自己的话题。其实我这种观念也不稀奇，在古代，东西方都流传着各种俚语和俏皮话，这些都是幽默感强的人在主动地寻找有趣。但在这个年代，这些俏皮话通过网络被定格下来，成了一个个“梗”，创造的空间似乎变小了。若是天天玩梗，在别人的笑料中深入钻研，这种乐趣其实是有限的，并且在我看来，也是种缺乏创造力的表现。幽默来源于我们的自身的敏感与智慧，应当属于自己。真正风趣的人只把别人的俚语作为一个启发或是交谈的配料，而不是话语的主体。说话的艺术，在一种更深层次的感觉当中。

在网络这个大平台上，“梗”其实也在很大程度上不同于从前的俚语，它缺乏一些智慧。网络早已成为大众消遣的主要工具。当一个人逃脱了白天繁重的学习、工作压力，你能指望他在网络里追求什么，自然是最肤浅却最可乐的笑料了！这些梗缺乏意义，只有乐趣。如果仍要类比到古代，那大概相当于斗虫、遛鸟。大众将生活里的不如意都转化为对“梗”的疯狂痴迷。譬如，很多人经常骂国足、笑国足，但这些笑的人却没有提出什么建设性建议。他们不是基于什么爱国情，而只是想在一个脱离了现实的地方，尽情发泄自己罢了。这也不是真正的乐趣。

当我看到别人玩梗，我也觉得很可乐。“梗”是非常娱乐化的事物，很适合作为大众的消遣。大众的需求到了，它就应运而生。但这种娱乐注定是肤浅的，可以作为某些时候的消遣，但不能作为生活的全部。梗的好玩背后，其实就是一种大众对娱乐的狂热追求，很多本不该成为梗的事却都变成了梗，很多严肃的事竟以一种好笑的形式被说出来。我认同梗的好玩，但不认同它原本如此。我怀疑有些事原来并非如此，只是为迎合大众变成这样，但这已很难考证了。

在我的认识中，我对大众所追求的一切，都有种近乎偏执的反感。他们从不思考、遵从本能。大众指的不一定是大多数人，而是指潮流里迷茫的人们。世界潮流不断更换，在任何一个时代，潮流都是奇怪的。它们总是在变，很无厘头。但我逐渐发现了它们的共性，即只代表集体意志，不代表个人。在很多情况下，潮流的产生都源自偶然，却竟成为所有人的共同爱好。梗的更新迭代是一种很好的对潮流的观察、研究对象。原本只是一个行为、一句话，很可笑，但不知怎么，在一夜之间，就成为全中国14亿人效仿的对象，这难道不可怕吗？对“梗”的恐惧也是我不玩梗的一个重要原因，我害怕被裹挟在这潮流里，或者说，不愿成为集体意志的一个附庸。

### 深入剖析

人民说：“要有梗。”于是就有了梗。从前茶余饭后聊闲天的乐趣被搬到电脑桌前，用来打趣的种种笑料逐渐被“梗”所统一。梗的风靡，只是大众追求娱乐的姿态在当下这个安定、便捷的时代的又一反映。只不过，当从大笑中清醒过来的人惊恐地发现了它对我们潜移默化的影响，这件事本身就没那么有趣了。

从前我们赖以娱乐的，多是些名人的绯闻或是各种传言。从前的名人大都是文化人，多少收敛些，可如今的互联网要追求平等，一方面带来让所有人成名的平等机会，一方面又把坐在电脑前的人的欲望平等地放大了。于是，两方一拍即合，梗越来越落于俗套，也越来越使人痴迷。

这种低俗的梗所带来的“新词”显然不能与作家的创造相提并论。若是仔细观察，我们就会看到，梗造词的套路大概都是把原本好好的字词句给安上了一个毫不相干的意思、用一种毫无逻辑的方式连接。面对这个词我们除了想到它所指代的梗，再想不出别的。而文学里的语言倾向于使不同的人——甚至同一个人——在面对这些词句时，能联想到不同意象，或者在不同时间生发出不同感受，并且它指代事物的功能更加符合逻辑和语境。我们应该明白，语言只是表达事物的一个手段，不能够把它当作事物本身来对待，而梗的蔓延就是要人们把它当作那唯一的、直观的事物的镜子。当语言取代了它所指代的形象或是取得了与它平等的地位，我们就无法如从前那样，深刻地描述身边丰富的世界了，因为我们所知道的语言都只能描绘单一事物。

失语者的出现就是该现象的一个直观反映，他们在频繁用梗中逐渐失去了组织复杂语言的能力，表达也越来越肤浅、简单。失去语言表达能力是极为可怕的，它不在于无法与人沟通，而在于我们失去了作为人类的一种本质，即描绘世界的能力，这比失去绘画能力或摄影能力要可怕的多，因为我们对这个世界的认识，大都来自于我们用以表示它的语言——可见的文字和不可见的思想。

此外，当一种语言为我们留出更多空间时，它才是好的。正因为语言赋予了我们选择的机会，作家才能依据个性旧词新用、创造新词。梗却残忍剥夺了这种机会，由于它的意思太过浅显，我们找不到改造的余地，因而我们的个性就无法伸展。久而久之，当所有的语言都成了这样，社会也就越来越缺乏创造力，人也越来越趋于一致。当个性和选择性被磨灭了，语言也就失去了意义。

当人逐渐屈服于这些肤浅的新语言，其思维也逐渐向它靠拢。实际上，语言永远不会可笑，可笑的是事物本身。在梗的体系里造出的词，往往令人捧腹。倘若是旧词新用，面对它在从前所描绘的事物，人们往往发出令人迷惑的笑。若是完全的“新词”呢，就要想方设法把它套用在周围的人和物上。这样一来，误解就产生了——人们把语言完完全全当作一种供其娱乐的东西，而忘记了它最初的作用。语言是我们对天地的度量，也是我们心灵的一面镜子。因此，无论是描绘世界还是反映个性，梗都没有做到。

由于这个世界的潮流是让人们享受肤浅的快感，众人也就把自己的欲望完全展露于世，他们的思维也越发肤浅。人们对复杂语言的处理和使用能力都在退化，然而，梗带来的巨大快感却又让人们恋恋不舍，不忍心完全割舍，寻求着折中的法子。这是一种非理性，也是人服从本能、屈服于环境的劣根性的表现。我不是在劝说人们放弃追求娱乐——实际上这是个兴趣问题——，而是希望人能够有节制、有选择地娱乐。我也不是在劝说人们理性地活着，将事事置于掌控之内，转而向古代的苦行者看齐。

几乎人人都喜欢娱乐，但娱乐作为人的本能，本是从放松自身、有益健康的角度出发，现今却反过来侵吞了人的语言、思维、性格……若是明白这点，再去寻求极致的快感，就是舍本逐末了。我们应当像弗洛伊德所号召的那样，将这本能升华为更有益于自身的活动，例如把兴趣点转移到感受语言魅力、自己组织语言上。

在这个无论外物还是自身的存在都在逐步淡化的时代，我们甚至比我们的原始人祖先更需要找到自我，在这躁动不安的世界里扎根。在我看来，语言就是为此发明的。它用它的包容而真切、亲切而神秘、感性而理性教导人们如何“再造世界”。等到人明白了这一点，我们也就大概知道了自己生命的轮廓，身体、心灵的各部分具有的意义。无论用语言交流还是思考，无疑都使我们更能塑造并稳固自己的存在。曾经我们的祖先就是以这种方式明白了语言中“我”字的独特性。遗憾的是，这个字在今天也逐渐变得千篇一律了。
