---
title: "和谐与冲突"
author: "AnchoraCloud"
date: "2024"
comments: false
word-counting: "1008"
categories: [社会,历史,文化]
include-after-body: 
    text: |
        <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js">
        </script>
        <span id="busuanzi_container_site_uv">
          🎰本文阅读量<span id="busuanzi_value_page_pv"></span>次
        </span>
---

中国人是讲求和谐的，待人和气、有礼。这一特质追溯到其源头，到上古时代，我们发现，这是为使众人团结起来，一同应付外部困难，以求得生存。

上层聪明的统治者，很明白这一番道理。他们规定历法、制定规则、确立公序良俗，使邻里和睦、官民协同、上下一心、家国一体，将所有人绑定在一起，维持社会稳定运行。

因为这更高法则的存在，个人做事时总要先顾虑社会上的影响。个人只有尊重社会公德，在交往中能够容忍他人，才可在社会上立足。久而久之，个人的利益都被置于集体之下，只有先尽到家庭、社会的责任，才能做自己的事。

我们可以想见，当人们紧紧抱成一团，融进这一大群体中，个人的声音便很难形成。东周和古希腊两个政权有部分时期是重合的，对比二者的文学，《诗经》作者都是匿名，许多诗被分类合订在一起，形成一个群体的声音；《荷马史诗》则带有很强的作者意识，里面的神话出自同一风格。但也有例外，东周末期的战国时代，社会秩序遭破坏，屈原便登上诗人的宝座，同时在思想界，各国人杰争相角逐、百家争鸣。而西方的希腊、罗马相继覆灭后，黑暗的中世纪便控制了人们的思想和生活。

因此，大凡和平年代，统治者就要绞尽脑汁维护社会秩序，遏止个人发声，“防民之口甚于防川”。为此不惜重农抑商、闭关锁国，放弃许多利益。稳定永远比繁盛重要。

然而，纵观历史，无论上位者多么努力，朝代总以冲突终结。万世江山、大同社会终归是黄粱一梦。这似乎表明，人性中有冲突的一面。人不是机器，假如被压抑得太深，是会奋起反抗的。在和平年代，这种冲突和对立尚未显现，而到了乱世，原先胆怯者都敢于展露自己的真实想法，勇武者则更是揭竿而起。

中国人以老为尊，注重老者身上的平和气质；西方人以少为美，注重青年人的傲气。这两者都是不完全的，因为它们都只是人的某一阶段。因此，中国的和谐终将被打破，西人的自由又总是造成混乱与争斗。而依我之见，应当把二者区以别矣。青年人应当有一种敢于打破现有陈规陋习的气势，发挥创造力，给社会带来新的声音。等TA年纪大了，就该收敛起来，宽以待人。和谐与冲突，本就是人的两种特质。冲突给世界毁坏掉一些、改造了一些；和谐则容许各人相安无事、基本的自由不受侵犯。这两者并不矛盾，反而可以相互促进：没有长者的宽容，青年怎能创新？没有青年的质疑，秩序终将腐化。只可惜，在现代世界，人们还未曾认识到这一点。在中国，遍地是沉默的大多数，缺乏生气；在美国，冲突遍地，人们为了种族、性别、观念相争执，战斗不息。
