---
title: "习相远也，性相近也"
date: "2024-04-14"
author: "AnchoraCloud"
comments: false
word-counting: "1398"
categories: [历史,文化]
include-after-body: 
    text: |
        <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js">
        </script>
        <span id="busuanzi_container_site_uv">
          🎰本文阅读量<span id="busuanzi_value_page_pv"></span>次
        </span>
---

我一直认为，婴儿眼中的世界和我们眼中的有很大的差异。婴儿第一次睁开眼睛，TA看到的是一个全然陌生的地方，意识忽然间，不知被什么东西填充了五感，于是TA本能地嚎啕大哭。但当TA成长，他发现有人竟比TA先来到这个世界，在这里生活的很好，那些人的生活，我们统称为历史。倘没有历史，我们会有一种婴儿般的不安全感。在这点上，人和动物的区别不大，后到者需要先到者的引导，否则就会茫然不知所措。安全感是历史带给我最基本的、也最重要的感觉。

当然，人类历史的复杂性远非动物所能媲美，而人类渴望记住历史的本能又没有改变，于是我们利用语言、文字把它们记述成书。但语言又无比复杂多变，有时很难把它准确无误地对应到原来的那个事物上，于是就产生了历史学家这个职业，专门钻研史书，为人们提供一种解释。

不同时代的历史学家有着不同的观念，也就在原有的典籍上留下不同的批注，前人的批注也有后人的批注，这样下去，批注的字数都要是原文的几十倍、数百倍，让人望而生畏。

这时，一定就会有人站出来斥责，历史上的细枝末节，真有必要这样细究吗，我们生活在现实里，难道不该着眼于现实吗？

的确，我们永远生活在现在。对于古代的事迹、古人的想法，我们不必一定认识到他们本来的想法。毕竟，有些过于久远之事已很难考证了。另外，看待同一句话、甚至同一个字，不同时代的人会引出不同的想法。历史总是要求进步，当后人了解到前人的事迹，TA应该着眼于那些启发TA思考的部分，吸取前人的教训，一些细枝末节的地方，比如“民可使由之，不可使知之”里孔子究竟是什么意思倒显得没那么重要，重要的是我们自己的意思。只有如此，人类社会才能不断进步。

好吧，对于“全人类”来说，因为无法求真而摒弃历史的真实，着眼于当下的进步，也许是最好的。但我并不很在乎“全人类”怎么样，如果只是去关注历史的精华，而全然轻视其糟粕，只是把它当做经验教训的话，历史就显得像一种工具，是为了社会进步而运作的。这样的历史是不完整的，因为精华与糟粕发源于同一个源头。

历史学家们为什么如此渴望认识到真实的历史人物，即便他们明知再严谨的考证都会存在局限？我想，这肯定不是做给古人看的，毕竟他们都死了，这是为了今人。各个时代的人，尽管在我们眼中大相径庭，但他们同我们总有一些相似之处，这是基于我们共有的人性。所谓“性相近也，习相远也”，我们本来是相同的，只是生在了不同环境里。想象着那些不同个性、活灵活现的历史人物，我仿佛看见了另一个自己，一个生长在另一个地方的我。想办法还原历史人物，是为了使我们安心：他们是一些有血有肉，和我们同样的人，而非替我们探查世界、做社会实验的工具。

我知道，一切对历史的认识都受着当下的影响，但有些东西是不变的。古人和我们一样都会思考、感受，有爱、有恨，有高尚的追求，有卑劣的想法。人性未曾改变。当我们从这个角度看待历史，我们也往往融入其中，而不仅仅局限于对于观念的争执上。诚然，我们都被打上了时代的烙印，孔子在他的年代，就是会说出“民可使由之，不可使知之”这类话；我们在现在的年代，也就是会说出“自由民主”这类话。但只有从历史人物的善恶两面看到了那些与善恶无关、与观念无关的东西，我们才能融入到历史长河中，在无限远的过去，在无限远的未来看到自己的身影，因而作为一颗水滴，与河流共同永恒地存在着。倘若只是放眼人生百年，拘泥于这百年的是非，把古人一一揪出来赞颂、批判，就失掉了在时代间自由游走的能力了。
