---
title: "说玩儿"
author: "AnchoraCloud"
date: "2024-06-29"
comments: false
word-counting: "1381"
categories: [理想,职业]
---

当人感到无聊时，心神如冰化为水，疏解到周围的空间里，仿佛即将消散，身体内部空无一物。为了阻止这一进程，人体自发地向外界寻求乐趣。于是精明的商人们就准备了各式的游戏，供人玩乐。从古至今，游戏的式样越发繁多，教人应接不暇。

但我更愿意谈论的是另一种玩。它并不来自外界的施与，而发自内心——从心中升起的对某一事物的兴致。它受着自己的掌控，因而更值得细细玩味。《世说》里记载了一则小故事。王子猷是东晋的一位大名士。一日夜间，他自睡梦中忽然醒来，在家里徘徊、啸咏良久，突然起了拜访朋友戴逵的心思。于是即便命仆从备小舟出发。舟行了一夜，夹杂着下了点小雪，第二天凌晨终于到他朋友家门口。这时，他忽然对周围仆从说：“咱们回去罢。”有人不解其意，怎么折腾半夜，好容易到了，又不去呢？王子猷道：“吾本乘兴而行，兴尽而返，何必见戴？”显然，王子猷此行，只是在玩。想玩便玩，欲止则止，随“兴”而行，自周围事物中创造乐趣。试问这样得来的玩乐，又怎会丧我之志呢？

玩的秘诀在于：全神贯注地做一件事，心底却并不把它当回事儿。

这并不意味着对人生、对事业的轻佻，恰恰相反，越是爱玩的人，越有机会做成一些事。他在做事时，是很轻松的，不对结果感到担忧，也不受社会环境的限制，不必在意别人的评判，可以自由地发挥。王世襄把他的古玩玩着玩着就享誉中外了；列文虎克就是在看门的时候常玩放大镜，才成了“显微镜之父”。乘着兴致而做事，使人更能专注于事物本身，不受忧虑与外界的干扰。正因他把自己的工作看得没那么重要，就容易产生意外之喜。

也正因着其目的的纯净，这些因玩而成功的人只是将成功看作副产品。爱玩的人、会玩的人能够从万事万物中创造乐趣，在无聊的世界里寻找到有趣之物。与这庞大的欢乐相比，成功带来的那点儿虚荣，也就不值一提了。王世襄总结自己一生时，绝口不提他那些荣誉、名作，只说“净玩儿了”。

大贤罗素说：“这个世界上到处是神奇的东西，它们在耐心地等待着我们变得更有智慧。”我每每读到这句话，心神都不由为之一振，一种无言的激情占据了我的胸腔。为了能够得到我在满足兴致的那一瞬所获得的欢愉，我愿意去尝试、去追寻、去等待，而乐此不疲。然而，一旦达成了目标，兴已尽，仿佛突然从欢愉的山顶跌下，落到寂寞的深渊里。过一阵子，内心又变得空虚与无聊，心神又行将消散。我常常想，假如有一位大智者，他把世上所有有趣的事物都发现了，把所有有趣的道理都研究透了，而我恰巧出生在他之后的年代，那么我活得该多么浑浑噩噩、行尸走肉啊！这样的话，我宁愿自杀。如此说来，我们总应当寻找到这样一类“玩物”——我们终其一生都无法得到它或参透它，而它永远在“耐心地等待着”。于是，我们就永远拥有着做事的激情，内心有所憧憬。携上希冀的干粮，我们便可踏上永恒之旅。至于其余的玩物，不过是旅途中的调味品罢了。

为了找到并确定这唯一的我们所钟意之物，我们需要作出选择。在这个一切东西都变得司空见惯的时代，尤其需要强大的辨别能力。但我们其实不必着急，沉静下来。每每对一件事产生了兴致，就抓住它，不让它从脑海里溜走，抛下一切全神贯注地去完成。久而久之，我们必然碰上“硬茬子”——仰之弥高，钻之弥坚，瞻之在前，忽焉在后。这时，我们便大可松一口气，再不用为心灵的空虚而忧愁了。在玩的道路上，每走一步，就有一步的乐趣；这种乐趣无穷无尽，同空虚感一道，延伸到渺远的未来，比生命本身更长久。
