---
title: "崇拜"
author: "AnchoraCloud"
date: "2023-06-03"
comments: false
word-counting: "1379"
categories: [社会,历史,文化]
include-after-body: 
    text: |
        <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js">
        </script>
        <span id="busuanzi_container_site_uv">
          🎰本文阅读量<span id="busuanzi_value_page_pv"></span>次
        </span>
---

早在“崇拜”一词被发明前，人类社会就已有了崇拜现象。对于神秘的大自然，西方人把它们整合为一至高无上的神，日夜向其祷告。中国人的神却有些杂乱，各行各业都要有一个，譬如灶王、土地公公、财神……实在不好整合。这种杂乱难以满足人类的崇拜欲。于是古人想了个折中的法子，在体系内融进了“半神”，教“孔子”统治了中国两千年。但到了今天，这“半神”倒是少见了，毕竟中国人的思想越发开放、自由了。另一方面，科学发展、媒介变迁粉碎了上帝。因此，在当今，人们的崇拜更多是对于某个实在、可见的人类个体了，崇拜现象也脱离了控制而成为个人的自由了。

在我看来，这类自发性的崇拜大致可分为两类。其一，被崇拜者在某些方面超过崇拜者。能力之差异引发了崇拜。其二，对某人的崇拜给予了崇拜者某种生活的目的。为这目的，他很容易成为狂热分子。这类人大多为社会中的失意者。总而言之，崇拜是一种个人对其所认为比之更高贵的个体而自然产生的带有仰视意味的情感，这种情感是如此普遍，以致成为人类社会的一大现象。

两次世界大战、冷战、文化大革命等种种灾难让人们开始反思崇拜之危害，极端主义思潮渐渐平息。二十一世纪，神智健全的人越来越多，在他们身上，主要存在第一类温和的崇拜。

崇拜变得更加纯粹和真诚，也就少有了危害。但崇拜的意义还需要人们继续发掘，不然就成了一个无用的情感了。

首先，应当明确：崇拜一个人的根本原因是为了自己。被崇拜者身上有我们所缺失之物，既然崇拜，就该努力弥补这一差距，不然其意义何在？因而，崇拜之中，行动的成分应大于情感。我们需利用崇拜给予的动力，用行动从被崇拜者身上汲取我们想要的，以发展自我。

既是为了自己，崇拜便不该是单一的。一个人在其人生的不同阶段，所思所想必然是会随之变化的。若长久地崇拜一个人，其生活一定是乏味的、僵化的。那些一生只崇拜孔子的儒生，日复一日遵守相同的礼仪道德，最终目标均是成为君子乃至圣人。也许他们还乐此不疲，我却觉得这样的生活相当无聊。每个领域都有大师，崇拜不同的人、不同的思想恰恰是成长之表现。这样，个人才更能发展出独立人格，拥有独特思想。不然，终岁便都被一个套子套住，不过是一辈子守着一潭井水的井底之蛙罢了。

更进一步，我认为崇拜在某种意义上可算作一种信仰了。崇拜者就好像被崇拜者的信徒。即便他并不只崇拜一个人，所持某些观点也可能与之相反，但崇拜者总是会继承一些被崇拜者之思想或能力，同时进行创新和发展。古希腊三位哲人苏格拉底、柏拉图和亚里士多德便是如此。思想基于崇拜，在这三人中以师生关系代代相传。继承者发展了这思想，而又各具特色，极大推动了哲学观的发展。崇拜就好像一个接力棒，被崇拜者将其传给崇拜者，后者奔跑了一段距离，将其传给下一个崇拜者。这接力棒上刻着接续与进步。人类就这样在追求智慧与能力的道路上渐行渐远。在不断崇拜不同个体的道路上，个人也在不断进步。当个人在其中发展出了完整的自我，崇拜便完成了它的使命。这时候，审视自我，我们自然会产生一种自豪感，自豪于自己之独立，也自豪于自己在人类发展征途上起的一点作用。崇拜这一古老的情感始终伴随着人类。它曾带来狂热，也曾带来反思、带来进步。回顾历史，真相便清晰可见了，我们不由赞叹其玄妙。是“崇拜”在混乱中带给我们秩序，若正确利用，它自然会完成它的使命，如纽带般，连接一个个时间节点和个体，进而串联起人类的历史与未来。
