---
title: "citywalk"
author: "AnchoraCloud"
date: "2023-12-23"
comments: false
word-counting: "1765"
categories: [消遣,哲思]
---

我是从一处马路的拐角出发的。那里停着几辆邮递车。一年前，这里还是核酸检查点，排着长队。放学后，我都会从学校或家赶来此地。当一个人爱一件事并长期做时，这会成为一个仪式；至于他那些无所谓做不做的事，长期做了以后，便会形成习惯。人们从不在意习惯，只是用它满足自己的需求，诸如刷牙、洗脸、走路、吃饭……但只有当习惯变成记忆时，它的乐趣才会显现。一群人在寒冷的大街上、在喧嚣的马路旁排着长队，慢慢悠悠地前行，左顾右盼、心不在焉。这是多么有趣的情境！只可惜，那用来测病毒的棉签结束了这一切，因为它，这个拐角处的一切都已被遗忘了——又或许它从未被留意。

从这里向西走，就遇上了一个交通要道，各色的机车，从这里或驶向二环，或奔向东四十条桥的环岛。顺着车流向北走，政府机关在街边设了一个很小的公园，一条小径在树丛中连接了东西，散布着一些活动设施。人很少，只有一两个老人在闲逛，剩下的就是铲雪的人，他们暂且顾不上这条小径，因此路上铺着薄薄的一层泥泞的雪。路的两侧是树丛，因而雪很白净，显得十分突兀。话说回来，这小公园在这嘈杂的城市中心也显得很突兀，水泥柏油的马路在这里断开，路过的人，即便少之又少，却都禁不住停下看看。但我又注意到，树丛中的鸟雀都不大活泼，躲在灌木的深处。因此，还有另一种解释：马路才是突兀的，城市的钢筋水泥把树木隔绝开来，鸟雀四散在这些孤岛之上，被关进了城市的监狱。

走上街边的天桥，横渡车流，来到街对面，再往南走过相似的小径，我惊讶地发现了一个广场，是一个宣传冬奥会的地方。我之前从未发现过它，尽管它离我家不远。因此，我来了些兴致，索性去看看。冬奥的吉祥物、奥运会创办者的雕像都是些惯常之物，除此以外，这广场的一大特色是充满了雪，这倒为冬奥增添了不少氛围。这可能与它原本的地势构造有关，又或者人故意不打扫，好让人玩雪。我的确遇见了几个在挖雪的孩子，他们的母亲在身边陪伴。我踏着厚厚的雪，爬上不平的地——这原先可能是草地，现已积满了雪。透过奥运五环的雕像，我看到不远处的高楼大厦。我知道，每座高楼都有无数人正在工作，不然，怎会留下老人、小孩在这里游玩？这宁静、祥和的氛围，我曾体会过，也许若干年后也能，但我当下却无法真切地领会它。写字楼又搅乱了我的心，我开始对我无所事事的行动感到不安。离开这冰天雪地的广场，我踏上了返程的路。

返程途中，我无意瞥见了一只喜鹊的尸体。它在一课行道树下，头朝下，羽毛向后舒展。除了这两处地方，它的身体几乎被啃食殆尽，留下薄薄的一层包着骨头的肉。这大概是野猫干的，我想。这场猎杀就发生在街道旁，死亡刚刚降临，就被城市的喧哗声所淹没，成为庞大都市里，又一个还未消失就已被遗忘的城市记忆。

这篇文章是以一种流水账的形式所写的，原因在于我的经历就是如此。我没有去到很远的地方，只是在家附近漫无目的地走了一个小时。这并不是由于我没有时间，而是因为我没有兴致。尽管我们声称那各色的楼阁宫殿、那错落有致的四合院才是北京的文化，但实际上，无论是古人还是今人，距离我们最近的都不会是那些红墙黄瓦，而是我们所真正生活着的地方。然而，那些真正留在我们记忆里的，却是遥远的事物，而那就在我们身边的事物，却被我们忽略了。这大概是由于人们总喜欢制造差异：中国有中国的特色、法国有法国的特色、日本有日本的特色……但实际上，这世界上的每座城市都有一些共有的东西，但它们却都因太过平常而被忽视了。但城市并不会忽视它们，城市有着自己的记忆。城市把这些记忆化作微小的痕迹，保存在城市的各处：雪地上的脚印、马路上方飞扬着的尘埃、墙壁的一处裂缝……城市以自己的方式记录着一切，这种记录自她诞生时就已开始了，直到今天，变化的只是记录的内容罢了。于我而言，尝试去理解城市的这些语言是极富乐趣的。人们过于看重自己给城市带来的东西——这些固然很重要，是这城市的基石——然而，我们却往往忽视了在漫长的发展中，城市想告诉我们的东西。实际上，在人所建造的城市内部，另有一座北京城，它是人计划之外的产物。你可能觉得它缺乏意义，因为它总是轻飘飘的，附着在我们所见的北京城上，薄薄的，几乎看不见。但倘若你再仔细观察，就会发现，不单是城市，你也被它所附着着，当你觉察到它时，你的身体也会变得轻盈。这座城市里仿佛有一位神灵，她就是这样轻飘飘的，在城市之中俯瞰它，认真地管理着那座看不见的城市。
