---
title: "我与日坛"
author: "AnchoraCloud"
date: "2023-11-21"
categories: [生活,美]
---

今天我所要介绍的，是我最爱去的地方——日坛公园。我在大概四五年前与她相遇。最初去的目的是跑步，因为那里场地较大，绕一圈1500米；弯道因而比较少；树也比较多。由于日坛离我家很近，我经常去那里，没过多久就跟她混熟了，在园子里轻车熟路，想去哪就去哪。因此，有了这层关系，我在日坛里的活动也逐渐从锻炼生发出些闲逛的意向，有时在那里待个三四十分钟，什么也不干，只是游山玩水：走过小径观察林间的鸟，登上假山眺望远处的中国尊，驻足听听空地上老人正拉着的小曲。其中我最爱去那里的时间，是下着小雨、园里的一切都较朦胧的时候。雨赶跑了多余的人，让日坛显出少有的清静，同时又为她增了些妩媚。这时我能体会到更多关于她的真实的细节。

日坛在北京的“九坛八庙”里，大概算是规模比较小的了，虽有近500年的历史，但唯一还有点古时的样子的，似乎只有位于其中心的祭日圜坛。那是一个四四方方的台子，禁止登上去；围着它走一圈，甚至看不见平台上铺的什么砖。我只有在下午4:30前才被准许围着它转转，因而往往要承受午日的曝晒。然而，我能在这座古代祭坛里发觉的历史痕迹，并不在她那些被翻新过的牌楼、宫殿，或是那个方正的圜坛，而在假山上空荡荡的小亭子里，在恰好停歇在屋檐一角的喜鹊的啼鸣声中，在无意瞥见的一位游人的背影上，在竹林掩映所拼凑出的断断续续的阴影间的空白里。总之，日坛带给我的厚重感，主要来源于她在当下所带给我的种种印象。她的红墙黄瓦、灰白的祭坛都是必需的，是我有机会静下心去感受她的基石，它们固然很重要，但不该完全占据我的感觉。

我以为，任何一个景观带给人的整体感受，都不该被它那些刻意去吸引人的部分所影响。日坛中那些精雕细琢、五彩斑斓的部分是嘉靖皇帝为了彰显皇家威严以及感动上天去设置的，同时也是匠人们刻意想让她漂亮点，教人流连忘返，因而非常耀眼夺目。然而这样的美景却只是生发于创造者的意志。我们往往会忽视她在这世界上带来的一些另外的东西。我们真正要去体会的，应当是她无意展现的，一些她所隐藏的，却因偶然而不经意暴露出来的新的印象。这些印象基于她本身，却又在某种程度上超越了她。我确信，其余那些名胜古迹、楼阁台榭，有很多比日坛更值得欣赏的，但由于我对日坛比较熟悉，而对其他地方的印象又只停留在紫禁城堂皇的殿堂、北海厚重的白塔、龙门石窟里庄严的佛像。因此，我最爱的地方，还是日坛。
